AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Serverless Specification template describing your function.
Resources:
  instanceStateChangeNotification:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ""
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::1234:role/xyz
      Environment:
        Variables:
          SLACK_CHANNEL: "#testing"
          # Use KMS instead
          SLACK_WEBHOOK_URL: >-
            https://hooks.slack.com/services/XYZ/XYZ/XYZ
